### ISSUE TITLE
rgdal archived

### ISSUE THREAD

**Issue by rsbivand** [MichaelChirico/geohashTools#42]
@MichaelChirico rgdal was archived yesterday, so please do move to submit an updated version of geohashTools as soon as possible. See https://github.com/r-spatial/evolution https://r-spatial.github.io/evolution/ for details.

**Comment by MichaelChirico** [comment]
Thanks for the nudge! I'd already fixed the issue on GitHub but forgot to submit to CRAN.

Happy retirement! Thanks again for your storied career!

**Comment by rsbivand** [comment]
Thanks for your cooperation!
